### ISSUE TITLE
coinmarketcapapi.CoinMarketCapAPIError: RESPONSE: 272ms ERR 401 "This API Key is invalid.": {}

### ISSUE THREAD

**Issue by tycooperaow** [rsz44/python-coinmarketcap#1]
I keep getting this error, even though I have an active and accurate api from coinmarketcap developers

**Comment by EneaMapelli** [comment]
Same here

**Comment by flepied** [comment]
I got bitten by this one too. Be sure to use an api key for https://sandbox.coinmarketcap.com/ if you use sandbox=True as this is not the same api key as the one for https://pro.coinmarketcap.com/.

**Comment by rsz44** [comment]
(Update for version 0.2)

Sorry for my late reply and thanks to @flepied :+1:, it was the right way to fix this error.

The sandbox parameters is now optional in version 0.2 because CoinMarket is using a default key for the sandbox mode. Corresponding to  [Quick Start Guide](https://coinmarketcap.com/api/documentation/v1/#section/Quick-Start-Guide) :

> Be sure to replace the API Key in sample code with your own and use API domain pro-api.coinmarketcap.com or use the test API Key b54bcf4d-1bca-4e8e-9a24-22ff2c3d462c for sandbox-api.coinmarketcap.com testing with our sandbox.coinmarketcap.com environment.

New usage in version 0.2 :

__Pro environnement : you have to give your API Key__

```
cmc = coinmarketcapapi.CoinMarketCapAPI('{YOUR_API_KEY}') # Pro environnement
```

__Sandbox : leave it blank__

```
cmc = coinmarketcapapi.CoinMarketCapAPI() # Sandbox environnement
```

In case of CoinMarketCap change the default (Sandbox) API key, you can also set it like this :

```
cmc = coinmarketcapapi.CoinMarketCapAPI('c54bcf4d-1bca-4e8e-9a24-22ff2c3d462b', sandbox=True) # Sandbox environnement
```
