### ISSUE TITLE
TypeError: unsupported format string passed to NoneType.__format__

### ISSUE THREAD

**Issue by cryofracture** [rsz44/python-coinmarketcap#2]
I am getting this error with requesting any quote other than BTC to USD. Code:

```
from coinmarketcapapi import CoinMarketCapAPI
from dotenv import load_dotenv
import argparse
import os

load_dotenv()


class CryptoQuote:
    def __init__(self, symbol, currency):
        
        self.quote = cmc.cryptocurrency_quotes_latest(symbol=symbol, convert=currency)
        self.price = self.quote.data[f'{symbol}']['quote'][f'{currency}']['price']
        self.symbol = str(symbol)
        self.circulating = self.quote.data[f'{symbol}']['circulating_supply']
        self.max = self.quote.data[f'{symbol}']['max_supply']
        self.market_cap = self.quote.data[f'{symbol}']['quote'][f'{currency}']['fully_diluted_market_cap']

    def __str__(self): 
        return f"Current quote for {self.symbol}: \nCurrent Price: ${self.price:,} \n" \
                f"Total Circulating Supply: {self.circulating:,} \n" \
                f"Max Supply of Token: {self.max:,} \n" \
                f"Market Cap of Token: ${self.market_cap:,}" 

if __name__ == "__main__":
    CMC_API_KEY = os.environ['CMC_API_KEY']

    cmc = CoinMarketCapAPI(CMC_API_KEY)
    parser = argparse.ArgumentParser(description="CoinmarketCap API tool to get a crypto qutoe ASAP.")
    parser.add_argument("--symbol", '-s', help="Which crypto symbol to check.", type=str, required=True, dest='symbol')
    parser.add_argument("--currency", '-c', help="Which fiat currency to convert to.", type=str, required=True, dest='currency')

    args = parser.parse_args()

    new_quote = CryptoQuote(args.symbol, args.currency)

    print(new_quote)
```

I have tried the following combinations:

* python3 get_price.py -s ETH -c USD
* python3 get_price.py -s ETH -c GBP
* python3 get_price.py -s CSPR -c USD
* python3 get_price.py -s ADA -c USD
* python3 get_price.py -s ADA -c GBP
* python3 get_price.py -s ETH -c JPY

All of my research suggests that It's my syntax but I can't pinpoint where I'm going wrong on this one.

**Comment by rsz44** [comment]
Hello,

Sorry for the long response time, I'm quite busy lately.

I saw your problem and it seems that it comes from the Max Supply, precisely the line `Max Supply of Token: {self.max:,} \n` (line 22 of your code) where `self.max == None`. Indeed, the Max supply could be `None` if the target does not define one. 

To see the response returned by the CoinMarketCap API we can add the `debug` flag `cmc = CoinMarketCapAPI(CMC_API_KEY, debug=True)`. And indeed, in the the response returned with ETH / USD we can see that `'max_supply': None`.

This also points to an error or quibble with the CoinMarketCap API documentation which gives a response where `max_supply` is a number (which is not necessarily the case obviously) ([See RESPONSE SCHEMA > data](https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyListingsLatest))

![CoinMarketCap API Documentation - coinmarketcap com](https://user-images.githubusercontent.com/22707219/131490902-ab3b7d2a-e10e-4950-8012-dd1da6438506.png)

To answer your problem, it would be wise to check in your `__init__` of your `CryptoQuote` class if this value is not equal to `None` and (maybe) assign it a default value if it's the case, like : `self.max = self.quote.data[f'{symbol}'].get('max_supply', 0) or 0` (line 16 of your code).

In the library, the choice has been made to leave the CoinMarket API response as interpreted by the `json` module in order to minimize the impact of incomplete schemas (as seen here).

I hope you'll find the answer to your problem here if you haven't solved it already.

**Comment by cryofracture** [comment]
@rsz44 thank you for the great writeup, and no worries on the delayed response. I just got a chance to test this and it worked like a charm. Thank you for showing me the debug tip and the max_supply = None info.

Script is working wonderfully now.
