### ISSUE TITLE
cryptocurrency_listings_latest not working

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [rsz44/python-coinmarketcap#6]
cmc.cryptocurrency_listings_latest(id=1) gives me this error. 

`coinmarketcapapi.CoinMarketCapAPIError: RESPONSE: 805ms ERR 400 ""id" is not allowed": {}`

I tested with slug and symbol but still doesn't work.

**Comment by rsz44** [comment]
Hello 👋,

Yep I get the same error, but it's quite normal here and verbose here : '"id" is not allowed'. As defined in the [documentation](https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyListingsLatest) this endpoint doesn't take an id as parameters because it must return a list to you: "Returns a paginated list of all active cryptocurrencies with latest market data."

Possible arguments for "cryptocurrency_listings_latest" on this date are (see complete info on documentation) : `start, limit, price_min, price_max, market_cap_min, market_cap_max, volume_24h_min, volume_24h_max, circulating_supply_min, circulating_supply_max, percent_change_24h_min, percent_change_24h_max, convert, convert_id, sort, sort_dir, cryptocurrency_type, tag, aux`.

What you are trying to do is probably on another endpoint, possibly (by giving an id) is [cmc.cryptocurrency_info(id=1)](https://coinmarketcap.com/api/documentation/v1/#operation/getV2CryptocurrencyInfo) (Returns all static metadata available for one or more cryptocurrencies). Or category too (they have id too)...

It depends on what you want to have ;).

Let me know if this was helpful or if you think it should work differently, I'll keep reading

**Comment by asdsadsaasd12312132** [comment]
What you said is right. /v2/cryptocurrency/quotes/latest gave me what I needed.
